services:
  front:
    build:
      context: ./front
    container_name: next_front
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: "npm run dev"
    depends_on:
      - back
    networks:
      - finpro-network

  back:
    build:
      context: ./back
    container_name: fastapi_back
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
    working_dir: /app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - finpro-network

  mail:
    image: axllent/mailpit
    container_name: mailpit_service
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - finpro-network

networks:
  finpro-network:
    driver: bridge
